# SPDX-License-Identifier: MIT
"""Speech-to-text helpers for Persona microphone input."""

from __future__ import annotations

import threading
from collections.abc import Iterator
from typing import TYPE_CHECKING, Optional, Protocol, Union, cast

import numpy as np

from ..dsp import resample_audio
from ..typing.aliases import AudioChunk

if TYPE_CHECKING:
    import torch


class _WhisperProcessorOutput(Protocol):
    """Protocol for tensor fields returned by a Whisper processor."""

    input_features: torch.Tensor
    attention_mask: Optional[torch.Tensor]


class _WhisperProcessor(Protocol):
    """Protocol for the processor operations used by the transcriber."""

    def __call__(
        self,
        audio: AudioChunk,
        *,
        sampling_rate: int,
        return_tensors: str,
        return_attention_mask: bool,
    ) -> _WhisperProcessorOutput:
        """Prepare one audio sample for Whisper."""

    def batch_decode(
        self,
        generated_ids: torch.Tensor,
        *,
        skip_special_tokens: bool,
    ) -> list[str]:
        """Decode generated Whisper token IDs into text.

        Args:
            generated_ids: Token IDs generated by the Whisper model.
            skip_special_tokens: Whether to omit special control tokens.
        """


class _WhisperModel(Protocol):
    """Protocol for the model operations used by the transcriber."""

    def eval(self) -> None:
        """Switch the model to evaluation mode."""

    def generate(self, **kwargs: Union[torch.Tensor, str]) -> torch.Tensor:
        """Generate token IDs from prepared Whisper inputs.

        Args:
            kwargs: Tensor and text inputs forwarded to Whisper generation.
        """

    def parameters(self) -> Iterator[torch.nn.Parameter]:
        """Iterate over the model parameters.

        Returns:
            Iterator[torch.nn.Parameter]: An iterator of model parameters.
        """


DEFAULT_PERSONA_SPEECH_MODEL_ID = "openai/whisper-large-v3-turbo"
PERSONA_SPEECH_END_DELAY_SECONDS = 1.5
WHISPER_SAMPLE_RATE = 16000


class WhisperTranscriber:
    """Lazily load and run one configurable Hugging Face Whisper model."""

    def __init__(self, model_id: str, language: Optional[str] = None) -> None:
        self.model_id = model_id.strip() or DEFAULT_PERSONA_SPEECH_MODEL_ID
        self.language = language.strip() if language and language.strip() else None
        self._processor: Optional[_WhisperProcessor] = None
        self._model: Optional[_WhisperModel] = None
        self._device: Optional[torch.device] = None
        self._dtype: Optional[torch.dtype] = None
        self._is_multilingual = True
        self._load_lock = threading.Lock()

    def _load_model(self) -> None:
        """Load the configured Whisper processor and model once."""
        if self._processor is not None and self._model is not None:
            return

        with self._load_lock:
            if self._processor is not None and self._model is not None:
                return

            import torch
            from transformers import (
                AutoModelForSpeechSeq2Seq,
                AutoProcessor,
                BitsAndBytesConfig,
            )

            if not torch.cuda.is_available():
                raise RuntimeError("can't load Whisper without a CUDA device")

            bnb_config = BitsAndBytesConfig(
                load_in_8bit=True,
            )
            model = cast(
                _WhisperModel,
                AutoModelForSpeechSeq2Seq.from_pretrained(
                    self.model_id,
                    dtype=torch.bfloat16,
                    low_cpu_mem_usage=True,
                    quantization_config=bnb_config,
                    device_map="auto",
                ),
            )
            model.eval()
            generation_config = getattr(model, "generation_config", None)
            self._is_multilingual = bool(
                getattr(generation_config, "is_multilingual", True)
            )
            self._processor = cast(
                _WhisperProcessor, AutoProcessor.from_pretrained(self.model_id)
            )
            self._model = model
            self._device = next(model.parameters()).device
            self._dtype = torch.bfloat16

    def _decode(
        self,
        audio: AudioChunk,
        sample_rate: int,
    ) -> str:
        """Prepare audio, generate Whisper tokens, and decode the transcript."""
        import torch

        self._load_model()
        processor = self._processor
        model = self._model
        device = self._device
        dtype = self._dtype
        if processor is None or model is None or device is None or dtype is None:
            raise RuntimeError("Whisper speech model did not initialize")

        processed = processor(
            np.asarray(audio, dtype=np.float32),
            sampling_rate=sample_rate,
            return_tensors="pt",
            return_attention_mask=True,
        )
        input_features = processed.input_features

        model_inputs: dict[str, Union[torch.Tensor, str]] = {
            "input_features": input_features.to(device=device, dtype=dtype),
        }
        attention_mask = processed.attention_mask
        if attention_mask is not None:
            model_inputs["attention_mask"] = attention_mask.to(device=device)
        if self._is_multilingual:
            model_inputs["task"] = "transcribe"
            if self.language is not None and self.language.lower() != "auto":
                model_inputs["language"] = self.language

        with torch.inference_mode():
            generated_ids = model.generate(**model_inputs)
        decoded = processor.batch_decode(generated_ids, skip_special_tokens=True)
        return decoded[0].strip() if decoded else ""

    def transcribe(
        self,
        audio: AudioChunk,
        sample_rate: int,
    ) -> str:
        """Transcribe one captured microphone snapshot.

        Args:
            audio: Mono or multi-channel microphone audio samples.
            sample_rate: Sample rate of the captured audio in hertz.

        Returns:
            str: The transcribed speech, or an empty string when no audio is available.

        Raises:
            ValueError: If the captured audio is not one- or two-dimensional.
        """
        if len(audio) <= 0:
            return ""

        mono_audio = np.asarray(audio, dtype=np.float32)
        if mono_audio.ndim == 2:
            mono_audio = np.asarray(
                np.mean(mono_audio, axis=1, dtype=np.float32),
                dtype=np.float32,
            )
        if mono_audio.ndim != 1:
            raise ValueError("Whisper speech input must be mono audio")
        if sample_rate != WHISPER_SAMPLE_RATE:
            resampled = resample_audio(
                mono_audio,
                sample_rate,
                WHISPER_SAMPLE_RATE,
            )
            mono_audio = np.asarray(
                np.mean(resampled, axis=1, dtype=np.float32),
                dtype=np.float32,
            )
        return self._decode(mono_audio, WHISPER_SAMPLE_RATE)
