"""Name day list derived from Polish name days, translated to English, and with Polish-only names removed."""

from __future__ import annotations

from datetime import date, datetime
from typing import Generator

NAMEDAYS: dict[str, list[str]] = {
    "01-01": [],
    "01-02": ["Basil", "Stephanie"],
    "01-03": ["Peter", "Genevieve"],
    "01-04": ["Angelica", "Angela", "Eugene", "Gregory", "Isabella"],
    "01-05": ["Edward", "Hannah", "Simon"],
    "01-06": ["Andrew", "Casper"],
    "01-07": ["Julian", "Lucian", "Valentine"],
    "01-08": [],
    "01-09": ["Anthony", "Julian", "Juliana"],
    "01-10": ["John", "Paul"],
    "01-11": ["Felix", "Matilda"],
    "01-12": ["Anthony", "Benedict", "Ernest"],
    "01-13": ["Veronica"],
    "01-14": ["Peter", "Nina"],
    "01-15": ["Alexander", "Paul"],
    "01-16": ["Marcel", "Kevin"],
    "01-17": ["Anthony", "John"],
    "01-18": ["Christine", "Peter"],
    "01-19": ["Andrew", "Bernard", "Henry", "Martha", "Sarah"],
    "01-20": ["Sebastian"],
    "01-21": ["Agnes", "Marcella"],
    "01-22": ["Martha", "Vincent"],
    "01-23": ["John", "Mary"],
    "01-24": ["Felicity", "Raphael", "Timothy"],
    "01-25": ["Paul", "Tatiana"],
    "01-26": ["Paula", "Pauline", "Wanda"],
    "01-27": ["Angelica", "Julian"],
    "01-28": ["Agnes", "Augustine", "Julian", "Charles", "Peter"],
    "01-29": ["Hannah"],
    "01-30": ["Felix", "Gerard", "Martin", "Martina", "Sebastian"],
    "01-31": ["John", "Peter"],
    "02-01": ["Ignatius", "Paul"],
    "02-02": ["Joanna", "Cornelius", "Mary"],
    "02-03": ["Oscar", "Stephen"],
    "02-04": ["Andrew", "Gilbert", "John", "Joanna", "Joseph", "Veronica"],
    "02-05": ["Agatha", "John", "Paul", "Peter"],
    "02-06": ["Anthony", "Dorothy", "Simon"],
    "02-07": ["Richard"],
    "02-08": ["John", "Paul", "Peter", "Sebastian"],
    "02-09": ["Bernard"],
    "02-10": ["Gabriel", "Hyacinth"],
    "02-11": ["Lucian", "Mary"],
    "02-12": ["Julian", "Nora"],
    "02-13": ["Gregory", "Jordan", "Catherine", "Linda"],
    "02-14": ["Joseph", "Conrad", "Christine", "Liliana", "Nicholas", "Cyril"],
    "02-15": ["Georgina", "Jordan", "Joseph"],
    "02-16": ["Bernard", "Juliana"],
    "02-17": ["Francis", "Julian", "Constantine"],
    "02-18": ["Albert", "Alberta", "Susanna"],
    "02-19": ["Arnold", "Henry", "Conrad"],
    "02-20": ["Leon"],
    "02-21": ["Felix", "Theodore"],
    "02-22": ["Martha", "Peter", "Victor"],
    "02-23": ["Damian", "Peter"],
    "02-24": ["Peter"],
    "02-25": ["Caesar"],
    "02-26": ["Alexander", "Evelina", "Alexandra"],
    "02-27": ["Alexander", "Anastasia", "Gabriel", "Gabriella"],
    "02-28": ["Joseph", "Roman"],
    "02-29": ["Roman"],
    "03-01": ["Anthony", "Antonia", "Amelia", "Felix", "Joanna", "Joseph", "Peter"],
    "03-02": ["Francis", "Helen", "Henry", "Christopher", "Michael", "Paul", "Peter"],
    "03-03": ["Jerome", "Marina"],
    "03-04": ["Adrian", "Adriana", "Eugene", "Lucy"],
    "03-05": ["Adrian", "Adriana", "Frederick", "John", "Olivia"],
    "03-06": ["Eugenia", "Jordan", "Rose", "Victor"],
    "03-07": ["Felicity", "Paul"],
    "03-08": ["Beatrice", "John", "Julian", "Stephen"],
    "03-09": ["Dominic", "Frances", "Catherine"],
    "03-10": ["Alexander"],
    "03-11": ["Benedict", "Edwin", "Constantine"],
    "03-12": ["Bernard", "Gregory", "Josephine"],
    "03-13": ["Ernest", "Christine", "Mark"],
    "03-14": ["Jacob", "Leon", "Matilda", "Michael"],
    "03-15": ["Clement", "Christopher", "Louise"],
    "03-16": ["Henrietta", "Herbert", "Isabella"],
    "03-17": ["Gertrude", "John", "Patrick"],
    "03-18": ["Alexander", "Cyril", "Edward"],
    "03-19": ["Joseph"],
    "03-20": ["Alexander", "Alexandra", "Claudia"],
    "03-21": ["Benedict", "Nicholas"],
    "03-22": ["Catherine", "Paul"],
    "03-23": ["Felix", "Catherine", "Peter"],
    "03-24": ["Gabriel", "Mark", "Simon"],
    "03-25": ["Lucy", "Mary"],
    "03-26": ["Emmanuel", "Felix", "Theodore"],
    "03-27": ["Benedict", "Ernest", "John", "Lydia"],
    "03-28": ["Angela", "Anthony", "John"],
    "03-29": ["Cyril"],
    "03-30": ["Amelia", "Angela", "John"],
    "03-31": ["Benjamin", "Cornelia"],
    "04-01": ["Catherine", "Theodora"],
    "04-02": ["Francis"],
    "04-03": ["Anthony", "Jacob", "Richard"],
    "04-04": ["Benedict"],
    "04-05": ["Irene", "Vincent"],
    "04-06": ["Ada", "Adam", "Catherine"],
    "04-07": [],
    "04-08": ["Caesar"],
    "04-09": ["Maya"],
    "04-10": ["Anthony", "Daniel", "Henry", "Michael"],
    "04-11": ["Philip", "Leon", "Mark"],
    "04-12": ["Andrew", "Julius", "Victor"],
    "04-13": ["John", "Justin", "Martin"],
    "04-14": ["Juliana", "Justin", "Mary"],
    "04-15": ["Anastasia"],
    "04-16": ["Julia"],
    "04-17": ["Jacob", "Joseph", "Clara", "Robert", "Stephen"],
    "04-18": [],
    "04-19": ["Leon"],
    "04-20": ["Agnes", "Simon", "Theodore"],
    "04-21": ["Bartholomew", "Felix", "Conrad"],
    "04-22": ["Kaya", "Theodore"],
    "04-23": ["Gerard", "Helen"],
    "04-24": ["Alexander", "Gregory", "Joanna"],
    "04-25": ["Mark"],
    "04-26": ["Mary"],
    "04-27": ["Andrew", "Peter"],
    "04-28": ["Mary", "Paul"],
    "04-29": ["Angelina", "Augustine", "Peter", "Robert"],
    "04-30": ["Bartholomew", "Jacob", "Catherine"],
    "05-01": ["Angela", "Philip", "Jacob", "Joseph", "Maya", "Sophia"],
    "05-02": [],
    "05-03": ["Alexander", "Antonia", "Mary"],
    "05-04": ["Gregory", "Michael", "Monica"],
    "05-05": ["Irene", "Theodore"],
    "05-06": ["John"],
    "05-07": ["Benedict"],
    "05-08": ["Mark", "Michael", "Peter"],
    "05-09": ["Gregory", "Caroline", "Nicholas"],
    "05-10": ["John"],
    "05-11": ["Philip", "Francis", "Ignatius", "Mira"],
    "05-12": ["Dominic", "John", "Joanna"],
    "05-13": ["Andrew", "Gloria", "Peter", "Robert"],
    "05-14": ["Victor"],
    "05-15": ["John", "Sophia"],
    "05-16": ["Andrew", "Simon"],
    "05-17": ["Bruno", "Veronica", "Victor"],
    "05-18": ["Alexander", "Alice", "Edwin", "Felix", "Irene"],
    "05-19": ["Augustine", "Nicholas", "Peter"],
    "05-20": ["Theodore", "Victoria"],
    "05-21": ["John", "Timothy", "Victor"],
    "05-22": ["Helen", "John", "Julia"],
    "05-23": ["Emily", "Yvonne", "John", "Michael"],
    "05-24": ["John", "Joanna", "Mary", "Susanna"],
    "05-25": ["Gregory", "Mary Magdalene"],
    "05-26": ["Philip", "Marianna", "Pauline", "Evelina"],
    "05-27": ["John", "Julius", "Lucian"],
    "05-28": ["Augustine", "Victor"],
    "05-29": ["Maximilian", "Mary", "Theodore", "Ursula"],
    "05-30": ["Felix", "Joanna"],
    "05-31": ["Angela", "Theodore"],
    "06-01": ["Bernard", "Jacob", "Conrad", "Nicodemus"],
    "06-02": ["Eugene", "Mary", "Marianna", "Mariana", "Nicholas", "Peter"],
    "06-03": ["Constantine", "Paula", "Tamara", "Olivia"],
    "06-04": ["Francis", "Charles"],
    "06-05": [],
    "06-06": ["Pauline"],
    "06-07": ["Anthony", "Paul", "Robert"],
    "06-08": [],
    "06-09": [],
    "06-10": [],
    "06-11": ["Felix"],
    "06-12": ["Antonia", "John", "Leon"],
    "06-13": ["Anthony", "Lucian", "Mary", "Tobias"],
    "06-14": ["Eliza", "Justin", "Justine"],
    "06-15": ["Angelina", "Yolanda"],
    "06-16": ["Alina", "Annette", "John", "Justine"],
    "06-17": ["Agnes", "Francis"],
    "06-18": ["Elizabeth", "Mark", "Paula"],
    "06-19": ["Juliana"],
    "06-20": ["Francis", "Michael", "Raphael"],
    "06-21": ["Alice", "Martha", "Theodore"],
    "06-22": ["Pauline"],
    "06-23": ["Joseph", "Peter", "Wanda"],
    "06-24": ["Emily", "John"],
    "06-25": ["Lucy"],
    "06-26": ["John", "Paul"],
    "06-27": ["Mary Magdalene"],
    "06-28": ["Joseph", "Leon", "Paul"],
    "06-29": ["Paul", "Peter"],
    "06-30": ["Emily"],
    "07-01": [],
    "07-02": ["Mary", "Peter"],
    "07-03": ["Hyacinth", "Leon"],
    "07-04": ["Elizabeth", "Joseph", "Julian", "Theodore"],
    "07-05": ["Anthony", "Bartholomew", "Jacob", "Caroline", "Michael"],
    "07-06": ["Dominic", "Lucy"],
    "07-07": ["Anthony", "Kira", "Peter", "Benedict", "Cyril", "Lucian"],
    "07-08": ["Adrian", "Adriana", "Elizabeth", "Eugene"],
    "07-09": ["Lucy", "Nicholas", "Veronica", "Sylvia"],
    "07-10": ["Alexander", "Amelia", "Angela", "Philip"],
    "07-11": [],
    "07-12": ["Andrew", "Felix", "Henry", "Paul", "Peter", "Veronica"],
    "07-13": ["Ernest", "Eugene", "Jacob", "Justine", "Sarah"],
    "07-14": ["Damian", "Francis", "Isabella"],
    "07-15": ["Daniel", "David", "Henry", "Ignatius"],
    "07-16": ["Andrew", "Mary Magdalene", "Stephen", "James"],
    "07-17": ["Alexander", "Andrew", "Mary Magdalene", "Annette"],
    "07-18": ["Caroline", "Robert", "Simon"],
    "07-19": ["Vincent"],
    "07-20": ["Paul"],
    "07-21": ["Andrew", "Daniel", "Pauline", "Victor"],
    "07-22": ["Mary Magdalene"],
    "07-23": [],
    "07-24": ["Anthony", "Christine"],
    "07-25": ["Jacob", "Christopher", "Valentina"],
    "07-26": ["Anna"],
    "07-27": ["Julia", "Martha", "Natalie"],
    "07-28": ["Marcella", "Victor"],
    "07-29": ["Constantine", "Mary", "Martha"],
    "07-30": ["Julia", "Marina"],
    "07-31": ["Helen", "Ignatius"],
    "08-01": ["Conrad", "Peter"],
    "08-02": ["Mary", "Stephen"],
    "08-03": ["Augusta", "Lydia", "Nicodemus", "Stephen"],
    "08-04": ["Dominic", "Mary"],
    "08-05": ["Mary"],
    "08-06": ["Jacob", "Stephen", "Vincent"],
    "08-07": ["Anna", "Dorothy"],
    "08-08": ["Cyril"],
    "08-09": ["John", "Roman"],
    "08-10": [],
    "08-11": ["Alexander", "Susanna"],
    "08-12": ["Clara", "Peter"],
    "08-13": ["Diana", "Helen", "John"],
    "08-14": [],
    "08-15": ["Mary", "Stephen"],
    "08-16": [],
    "08-17": [
        "Anastasia",
        "Angelica",
        "Anita",
        "Eliza",
        "Hyacinth",
        "Joanna",
        "Juliana",
        "Jeanne",
    ],
    "08-18": ["Helen", "Clara"],
    "08-19": ["Emily", "John", "Julian", "Julius", "Peter"],
    "08-20": ["John", "Samuel"],
    "08-21": ["Philippa", "Francis", "Joanna"],
    "08-22": ["Caesar", "Mary", "Timothy"],
    "08-23": ["Philip"],
    "08-24": ["Bartholomew", "Joanna", "Michaela", "Albert"],
    "08-25": ["Gregory", "Michael"],
    "08-26": ["Joanna", "Constantine", "Mary"],
    "08-27": ["Caesar", "Joseph", "Monica", "Theodore"],
    "08-28": ["Adeline", "Alexander", "Alexis", "Augustine", "Patricia"],
    "08-29": ["John"],
    "08-30": ["Rebecca", "Rose"],
    "08-31": ["Pauline", "Raymond"],
    "09-01": [],
    "09-02": ["Eliza", "Henry", "Julian", "Stephen", "Tobias"],
    "09-03": ["Anthony", "Bartholomew", "Isabella", "John", "Simon", "Vincent"],
    "09-04": ["Ida", "Lillian", "Rose"],
    "09-05": ["Dorothy", "Justine"],
    "09-06": ["Beatrice", "Eugene", "Michael"],
    "09-07": ["Mark", "Regina", "Richard"],
    "09-08": ["Adrian", "Adriana", "Mary", "Clementine"],
    "09-09": ["Augusta", "Peter"],
    "09-10": ["Nicholas"],
    "09-11": ["Felix", "Hyacinth", "John"],
    "09-12": ["Mary", "Peter"],
    "09-13": ["Alexander", "Philip"],
    "09-14": ["Bernard", "Roxanne", "Simon"],
    "09-15": ["Mary", "Nicodemus"],
    "09-16": ["Edith", "Eugenia", "Francis", "Camilla", "Cornelius", "Lucy", "Victor"],
    "09-17": ["Francis", "Justin", "Justine", "Theodora"],
    "09-18": ["Irene", "Joseph", "Stephanie"],
    "09-19": ["Constance", "Theodore"],
    "09-20": ["Agnes", "Barbara", "Philippa", "Irene", "Clement"],
    "09-21": ["Jonah", "Matthew", "Mira"],
    "09-22": ["Maurice"],
    "09-23": ["Elizabeth", "Christopher", "Peter"],
    "09-24": ["Gerard", "Mary", "Theodore"],
    "09-25": ["Aurelia", "Francis", "Peter", "Vincent"],
    "09-26": ["Justine"],
    "09-27": ["Damian"],
    "09-28": ["John", "Mark"],
    "09-29": ["Michael", "Raphael", "Gabriel"],
    "09-30": ["Gregory", "Jerome", "Victor", "Sophia"],
    "10-01": ["John"],
    "10-02": [],
    "10-03": ["Gerard", "Josephine", "Theresa"],
    "10-04": ["Edwin", "Francis", "Conrad"],
    "10-05": ["Justin"],
    "10-06": ["Arthur", "Roman"],
    "10-07": ["Justine", "Mark", "Mary", "Stephen"],
    "10-08": ["Bridget", "Martin"],
    "10-09": ["John", "Louis", "Sarah"],
    "10-10": ["Francis", "Pauline"],
    "10-11": ["Mary"],
    "10-12": ["Maximilian"],
    "10-13": ["Daniel", "Edward", "Nicholas"],
    "10-14": ["Alan", "Bernard", "Dominic"],
    "10-15": ["Teresa"],
    "10-16": ["Aurelia", "Gerard", "Gregory"],
    "10-17": ["Victor"],
    "10-18": ["Julian"],
    "10-19": ["Ferdinand", "Peter", "Olivia"],
    "10-20": ["Irene"],
    "10-21": ["Bernard", "Celine", "Elizabeth", "Ursula"],
    "10-22": ["Philip"],
    "10-23": ["Ignatius", "John", "Marlene", "Roman", "Theodore"],
    "10-24": ["Anthony", "Philip", "Martin", "Raphael"],
    "10-25": ["Daria"],
    "10-26": ["Lucian"],
    "10-27": ["Yvonne", "Vincent"],
    "10-28": ["Simon", "Thaddeus"],
    "10-29": ["Francis", "Theodore", "Violetta"],
    "10-30": ["Edmund"],
    "10-31": ["Anthony"],
    "11-01": ["Andrew"],
    "11-02": ["Tobias"],
    "11-03": ["Caesar", "Hubert", "Sylvia"],
    "11-04": ["Charles"],
    "11-05": ["Elizabeth", "Jacob"],
    "11-06": ["Felix", "Leonard"],
    "11-07": ["Anthony"],
    "11-08": ["Victor"],
    "11-09": ["Genevieve", "Theodore"],
    "11-10": ["Andrew", "Lena", "Leon", "Stephen"],
    "11-11": ["Anastasia", "Bartholomew", "Martin", "Theodore"],
    "11-12": ["Jonah", "Martin", "Renata"],
    "11-13": ["Eugene", "John", "Nicholas"],
    "11-14": ["Agatha", "Damian", "Elizabeth", "Joseph", "Judith"],
    "11-15": ["Arthur", "Joseph"],
    "11-16": ["Edmund", "Mark", "Mary", "Paul", "Peter"],
    "11-17": ["Gregory"],
    "11-18": ["Agnes", "Angela", "Roman"],
    "11-19": ["Elizabeth", "Paul"],
    "11-20": ["Edmund", "Felix"],
    "11-21": ["Conrad", "Mary", "Peter", "Regina"],
    "11-22": ["Cecilia", "Mark"],
    "11-23": ["Adela", "Clement"],
    "11-24": ["Emily", "Emma", "Francis", "Gerard", "John"],
    "11-25": ["Catherine"],
    "11-26": ["John", "Conrad", "Leonard"],
    "11-27": ["Dominic", "Maximilian"],
    "11-28": ["Gregory", "Jacob"],
    "11-29": ["Frederick"],
    "11-30": ["Andrew", "Justine", "Constantine"],
    "12-01": ["Edmund", "Natalie"],
    "12-02": ["Aurelia", "Pauline"],
    "12-03": ["Francis"],
    "12-04": ["Barbara", "Jerome", "Christian", "Peter"],
    "12-05": ["Christine"],
    "12-06": ["Nicholas", "Nicole"],
    "12-07": ["Martin"],
    "12-08": ["Mary"],
    "12-09": [],
    "12-10": ["Andrew", "Daniel", "Judith", "Julia", "Mary"],
    "12-11": ["Daniela", "Julia", "Stephen"],
    "12-12": ["Alexander"],
    "12-13": ["Lucy"],
    "12-14": [],
    "12-15": ["Celine", "Ignatius", "Nina"],
    "12-16": ["Alina"],
    "12-17": ["Yolanda"],
    "12-18": [],
    "12-19": ["Benjamin", "Darius", "Gabriella", "Timothy"],
    "12-20": ["Dominic"],
    "12-21": [],
    "12-22": ["Beatrice", "Frances"],
    "12-23": ["Victoria"],
    "12-24": ["Adam", "Adela", "Eve", "Gregory"],
    "12-25": ["Anastasia", "Eugenia", "Peter", "Nicholas"],
    "12-26": ["Stephen", "Sylvia", "Anna", "Marie"],
    "12-27": ["Caesar", "John"],
    "12-28": ["Anthony", "Emma"],
    "12-29": ["David", "Dominic", "Martin"],
    "12-30": ["David", "Eugene", "Catherine"],
    "12-31": ["Cornelius", "Sebastian"],
}


def _key(month: int, day: int) -> str:
    return f"{month:02d}-{day:02d}"


def get_names(month: int, day: int) -> list[str]:
    """Return the English-only name-day names for a month/day pair.

    Args:
        month: The month number to look up.
        day: The day number to look up.

    Returns:
        list[str]: The matching English name-day names.
    """
    return list(NAMEDAYS.get(_key(month, day), []))


def get_names_for_date(value: date | datetime | str) -> list[str]:
    """Return names for a date, datetime, or YYYY-MM-DD / MM-DD string.

    Args:
        value: A date-like value identifying the day to query.

    Returns:
        list[str]: The matching English name-day names.
    """
    if isinstance(value, datetime):
        return get_names(value.month, value.day)
    if isinstance(value, date):
        return get_names(value.month, value.day)
    if isinstance(value, str):
        parts = value.split("-")
        if len(parts) == 3:
            return get_names(int(parts[1]), int(parts[2]))
        if len(parts) == 2:
            return get_names(int(parts[0]), int(parts[1]))
    raise TypeError(
        "value must be a date, datetime, YYYY-MM-DD string, or MM-DD string"
    )


def find_dates_for_name(name: str) -> list[str]:
    """Return all MM-DD dates where the given English name appears.

    Args:
        name: The English name to search for.

    Returns:
        list[str]: Every ``MM-DD`` entry that contains the supplied name.
    """
    needle = name.casefold()
    return [
        d for d, names in NAMEDAYS.items() if any(n.casefold() == needle for n in names)
    ]


def has_nameday(name: str, value: date | datetime | str) -> bool:
    """Return whether the given English name is present on the supplied date.

    Args:
        name: The English name to check.
        value: A date-like value identifying the day to query.

    Returns:
        bool: ``True`` when the name appears on that date, otherwise ``False``.
    """
    needle = name.casefold()
    return any(n.casefold() == needle for n in get_names_for_date(value))


def iter_namedays() -> Generator[str | list[str], None, None]:
    """Iterate over ``(MM-DD, names)`` pairs.

    Returns:
        Generator[str | list[str], None, None]: A generator that yields each date
            key followed by its corresponding list of names.
    """
    for item in NAMEDAYS.items():
        yield from item
