# SPDX-License-Identifier: Apache-2.0
"""Shared timing and buffering constants for Celune's speech pipeline."""

import time


_SFX_DUCK_GAIN = 0.25
_SFX_DUCK_FADE_SECONDS = 0.15
_LEGACY_BUFFER_SECONDS = 10.0
_SMART_BUFFER_REALTIME_SPEED = 1.05
_SMART_BUFFER_PROTECTED_PLAYBACK_SECONDS = 20.0
_SMART_BUFFER_MIN_SECONDS = 0.35
_SMART_BUFFER_MIN_SPEED_SAMPLE_SECONDS = 0.75
_SMART_BUFFER_MAX_SECONDS = 20.0
_SMART_BUFFER_COMPLETE_BELOW_SPEED = 0.5
_SMART_BUFFER_SMOOTHING = 0.35
_MAX_YOUTUBE_DOWNLOAD_RETRIES = 3
_PLAYBACK_BUFFER_MIN_SECONDS = 2.0
_PLAYBACK_BUFFER_MAX_SECONDS = 12.0
_PLAYBACK_BUFFER_CRITICAL_MAX_SECONDS = 30.0
_PLAYBACK_BUFFER_STARTUP_GRACE_SECONDS = 0.25
_PLAYBACK_CONTENTION_SAMPLE_SECONDS = 0.25
_PLAYBACK_CONTENTION_CPU_START = 75.0
_PLAYBACK_CONTENTION_CPU_CRITICAL = 95.0
_PLAYBACK_CONTENTION_LAG_START_SECONDS = 0.015
_PLAYBACK_CONTENTION_LAG_CRITICAL_SECONDS = 0.1
_PLAYBACK_CONTENTION_STABLE_DECAY = 0.96
_PLAYBACK_CONTENTION_REBUFFER_LEVEL = 0.5
_PLAYBACK_TRACE_INTERVAL_SECONDS = 0.5
_PIPELINE_CPU_MAX_BUFFER_SECONDS = _PLAYBACK_BUFFER_MAX_SECONDS
_PIPELINE_CPU_MAX_DRAIN_ITEMS = 4
_PIPELINE_CPU_YIELD_SECONDS = 0.001


def _monotonic_time() -> float:
    """Return the monotonic clock used for pipeline timing."""
    return time.monotonic()
