# SPDX-License-Identifier: MIT
"""Contracts for Celune's future local-only agent mode."""

from collections.abc import Mapping

from ..exceptions import (
    NeedleCheckpointError,
    NeedleSelectionError,
    NeedleUnsupportedConverterError,
)
from ..typing.agent import (
    AgentAbortReason,
    AgentApprovalDecision,
    AgentApprovalRequest,
    AgentApprovalResponse,
    AgentCancellationReason,
    AgentChoiceOption,
    AgentChoiceRequest,
    AgentChoiceResponse,
    AgentClassificationFailure,
    AgentClassificationFailureKind,
    AgentClassificationResult,
    AgentContextCompactor,
    AgentContext,
    AgentFailureReason,
    AgentInputClassification,
    AgentInterruption,
    AgentInterruptionKind,
    AgentOutput,
    AgentPermissionDecision,
    AgentPermissionEvaluation,
    AgentPermissionMetadata,
    AgentPermissionPolicy,
    AgentPermissionReason,
    AgentRequest,
    AgentResponseCallback,
    AgentResponder,
    AgentRoute,
    AgentSession,
    AgentSessionState,
    AgentTask,
    AgentTaskConfig,
    AgentTaskState,
    AgentTool,
    AgentToolArgumentSchema,
    AgentToolBehavior,
    AgentToolDangerLevel,
    AgentToolExecutionStatus,
    AgentToolExecutor,
    AgentToolResultHandler,
    AgentToolSchema,
    AgentToolSelector,
    AgentToolValueType,
    AgentTokenCounter,
    AgentPlanner,
    NeedleToolCall,
    NeedleToolCatalog,
    NeedleToolDefinition,
    NeedleToolParameter,
    NeedleToolParameterSpec,
    NeedleToolSelection,
    ToolCall,
    ToolExecutionResult,
    ToolResult,
    ValidatedToolCall,
)
from ..modes import mode_allows_agents, resolve_operation_mode
from ..typing.common import JSONSerializable
from .needle import (
    NEEDLE_MODEL_ID,
    NEEDLE_MODEL_REVISION,
    NeedleHandler,
    NeedleToolSelector,
    NeedleTokenizer,
    convert_needle_safetensors,
)
from .needle_checkpoint import (
    NEEDLE_PICKLE_FILE,
    NeedleCheckpointMetadata,
    NeedlePickleConverter,
    NeedlePreparedCheckpoint,
    NeedleTensorInventory,
    prepare_needle_checkpoint,
    validate_needle_safetensors,
)
from .needle_model import NeedleConfig, NeedleModel
from .runtime import AgentRuntime, DefaultAgentPermissionPolicy
from .routing import AgentInputRouter


def agent_mode_enabled(
    config: Mapping[str, JSONSerializable],
) -> bool:
    """Return whether the global config selects the agent operation mode."""
    return mode_allows_agents(resolve_operation_mode(config))


__all__ = [
    "NEEDLE_MODEL_ID",
    "NEEDLE_MODEL_REVISION",
    "NEEDLE_PICKLE_FILE",
    "AgentAbortReason",
    "AgentApprovalDecision",
    "AgentApprovalRequest",
    "AgentApprovalResponse",
    "AgentCancellationReason",
    "AgentChoiceOption",
    "AgentChoiceRequest",
    "AgentChoiceResponse",
    "AgentClassificationFailure",
    "AgentClassificationFailureKind",
    "AgentClassificationResult",
    "AgentContext",
    "AgentContextCompactor",
    "AgentFailureReason",
    "AgentInputClassification",
    "AgentInputRouter",
    "AgentInterruption",
    "AgentInterruptionKind",
    "AgentOutput",
    "AgentPermissionDecision",
    "AgentPermissionEvaluation",
    "AgentPermissionMetadata",
    "AgentPermissionPolicy",
    "AgentPermissionReason",
    "AgentPlanner",
    "AgentRequest",
    "AgentResponder",
    "AgentResponseCallback",
    "AgentRoute",
    "AgentRuntime",
    "AgentSession",
    "AgentSessionState",
    "AgentTask",
    "AgentTaskConfig",
    "AgentTaskState",
    "AgentTokenCounter",
    "AgentTool",
    "AgentToolArgumentSchema",
    "AgentToolBehavior",
    "AgentToolDangerLevel",
    "AgentToolExecutionStatus",
    "AgentToolExecutor",
    "AgentToolResultHandler",
    "AgentToolSchema",
    "AgentToolSelector",
    "AgentToolValueType",
    "DefaultAgentPermissionPolicy",
    "NeedleCheckpointError",
    "NeedleCheckpointMetadata",
    "NeedleConfig",
    "NeedleHandler",
    "NeedleModel",
    "NeedlePickleConverter",
    "NeedlePreparedCheckpoint",
    "NeedleSelectionError",
    "NeedleTensorInventory",
    "NeedleTokenizer",
    "NeedleToolCall",
    "NeedleToolCatalog",
    "NeedleToolDefinition",
    "NeedleToolParameter",
    "NeedleToolParameterSpec",
    "NeedleToolSelection",
    "NeedleToolSelector",
    "NeedleUnsupportedConverterError",
    "ToolCall",
    "ToolExecutionResult",
    "ToolResult",
    "ValidatedToolCall",
    "agent_mode_enabled",
    "convert_needle_safetensors",
    "prepare_needle_checkpoint",
    "validate_needle_safetensors",
]
