# SPDX-License-Identifier: MIT
"""Compatibility exports for the relocated agent type definitions."""

# This module intentionally mirrors the lazy typing-package export list.
# pylint: disable=duplicate-code

from ..typing.agent import (
    AgentAbortReason,
    AgentApprovalDecision,
    AgentApprovalRequest,
    AgentApprovalResponse,
    AgentCancellationReason,
    AgentChoiceOption,
    AgentChoiceRequest,
    AgentChoiceResponse,
    AgentClassificationResult,
    AgentContext,
    AgentFailureReason,
    AgentInputClassification,
    AgentInterruption,
    AgentInterruptionKind,
    AgentOutput,
    AgentRequest,
    AgentResponseCallback,
    AgentRoute,
    AgentSession,
    AgentSessionState,
    AgentTask,
    AgentTaskConfig,
    AgentTaskState,
    AgentTool,
    AgentToolArgumentSchema,
    AgentToolBehavior,
    AgentToolDangerLevel,
    AgentToolExecutionStatus,
    AgentToolSchema,
    AgentToolValueType,
    NeedleToolCall,
    NeedleToolCatalog,
    NeedleToolDefinition,
    NeedleToolParameter,
    NeedleToolParameterSpec,
    NeedleToolSelection,
    ToolCall,
    ToolExecutionResult,
    ToolResult,
    ValidatedToolCall,
)

__all__ = [
    "AgentAbortReason",
    "AgentApprovalDecision",
    "AgentApprovalRequest",
    "AgentApprovalResponse",
    "AgentCancellationReason",
    "AgentChoiceOption",
    "AgentChoiceRequest",
    "AgentChoiceResponse",
    "AgentClassificationResult",
    "AgentContext",
    "AgentFailureReason",
    "AgentInputClassification",
    "AgentInterruption",
    "AgentInterruptionKind",
    "AgentOutput",
    "AgentRequest",
    "AgentResponseCallback",
    "AgentRoute",
    "AgentSession",
    "AgentSessionState",
    "AgentTask",
    "AgentTaskConfig",
    "AgentTaskState",
    "AgentTool",
    "AgentToolArgumentSchema",
    "AgentToolBehavior",
    "AgentToolDangerLevel",
    "AgentToolExecutionStatus",
    "AgentToolSchema",
    "AgentToolValueType",
    "NeedleToolCall",
    "NeedleToolCatalog",
    "NeedleToolDefinition",
    "NeedleToolParameter",
    "NeedleToolParameterSpec",
    "NeedleToolSelection",
    "ToolCall",
    "ToolExecutionResult",
    "ToolResult",
    "ValidatedToolCall",
]
