# SPDX-License-Identifier: Apache-2.0
"""Unified Celune type package with lazy re-exports."""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .analysis import (
        EmbeddingModel,
        EmbeddingOutput,
        EmbeddingPayload,
        EmbeddingProcessor,
        TextConfig,
        TextConfigValue,
        VoiceMatch,
    )
    from .backends import (
        BackendModel,
        MiniModel,
        MiniPromptState,
        ModelT,
    )
    from .celune import (
        ErrorCallback,
        Generative,
        IdleCallback,
        InputStateCallback,
        MessageCallback,
        NormalizerTokenizer,
        ProgressCallback,
        QueueAvailableCallback,
        ReleasableObject,
        SupportsClose,
        SupportsUnload,
        VoiceChangedCallback,
        VoiceLockStateCallback,
    )
    from .cevoice import (
        Manifest,
        ManifestValue,
        VoiceManifest,
    )
    from .common import (
        JSON,
        RGB,
        Config,
        JSONSerializable,
        TerminalConfig,
        VideoMetadataScalar,
        VramTier,
    )
    from .extensions import (
        DevLogCallable,
        GetStateCallable,
        LogCallable,
        PlayCallable,
        SayCallable,
        SetVoiceCallable,
        StatusCallable,
        ThinkCallable,
        WaitUntilReadyCallable,
    )
    from .persona import (
        ChatMessagePayload,
        ChatTemplateRenderer,
        ContentItem,
        ImageContentItem,
        JSONDict,
        MessageContent,
        ModelGenerateKwargValue,
        PersonaModel,
        PersonaProcessor,
        PersonaTokenizer,
        ProcessorKwargValue,
        Role,
        TextContentItem,
        VideoContentItem,
        VideoInputWithMetadata,
        VideoMetadata,
        VisionInput,
        VisionProcessorOutput,
    )
    from .pipeline import (
        AudioChunk,
        AudioQueueItem,
        SpeechStreamItem,
        SpeechStreamQueue,
        TextQueueItem,
    )
    from .ui import (
        CeluneBaseUI,
        CeluneHeadlessBaseUI,
        CeluneTextualUI,
    )
    from .utils import (
        CallerInfo,
        LanguageResult,
    )

_MODULE_EXPORTS = {
    "AudioChunk": "pipeline",
    "AudioQueueItem": "pipeline",
    "BackendModel": "backends",
    "CallerInfo": "utils",
    "CeluneBaseUI": "ui",
    "CeluneHeadlessBaseUI": "ui",
    "CeluneTextualUI": "ui",
    "ChatMessagePayload": "persona",
    "ChatTemplateRenderer": "persona",
    "Config": "common",
    "ContentItem": "persona",
    "DevLogCallable": "extensions",
    "EmbeddingModel": "analysis",
    "EmbeddingOutput": "analysis",
    "EmbeddingPayload": "analysis",
    "EmbeddingProcessor": "analysis",
    "ErrorCallback": "celune",
    "Generative": "celune",
    "GetStateCallable": "extensions",
    "IdleCallback": "celune",
    "ImageContentItem": "persona",
    "InputStateCallback": "celune",
    "JSON": "common",
    "JSONDict": "persona",
    "JSONSerializable": "common",
    "LanguageResult": "utils",
    "LogCallable": "extensions",
    "Manifest": "cevoice",
    "ManifestValue": "cevoice",
    "MessageCallback": "celune",
    "MessageContent": "persona",
    "MiniModel": "backends",
    "MiniPromptState": "backends",
    "ModelGenerateKwargValue": "persona",
    "ModelT": "backends",
    "NormalizerTokenizer": "celune",
    "PersonaModel": "persona",
    "PersonaProcessor": "persona",
    "PersonaTokenizer": "persona",
    "PlayCallable": "extensions",
    "ProcessorKwargValue": "persona",
    "ProgressCallback": "celune",
    "QueueAvailableCallback": "celune",
    "ReleasableObject": "celune",
    "RGB": "common",
    "Role": "persona",
    "SayCallable": "extensions",
    "SetVoiceCallable": "extensions",
    "SpeechStreamItem": "pipeline",
    "SpeechStreamQueue": "pipeline",
    "StatusCallable": "extensions",
    "SupportsClose": "celune",
    "SupportsUnload": "celune",
    "TerminalConfig": "common",
    "TextConfig": "analysis",
    "TextConfigValue": "analysis",
    "TextQueueItem": "pipeline",
    "TextContentItem": "persona",
    "ThinkCallable": "extensions",
    "VideoContentItem": "persona",
    "VideoInputWithMetadata": "persona",
    "VideoMetadata": "persona",
    "VideoMetadataScalar": "common",
    "VisionInput": "persona",
    "VisionProcessorOutput": "persona",
    "VoiceChangedCallback": "celune",
    "VoiceLockStateCallback": "celune",
    "VoiceManifest": "cevoice",
    "VoiceMatch": "analysis",
    "VramTier": "common",
    "WaitUntilReadyCallable": "extensions",
}

__all__ = [
    "JSON",
    "RGB",
    "AudioChunk",
    "AudioQueueItem",
    "BackendModel",
    "CallerInfo",
    "CeluneBaseUI",
    "CeluneHeadlessBaseUI",
    "CeluneTextualUI",
    "ChatMessagePayload",
    "ChatTemplateRenderer",
    "Config",
    "ContentItem",
    "DevLogCallable",
    "EmbeddingModel",
    "EmbeddingOutput",
    "EmbeddingPayload",
    "EmbeddingProcessor",
    "ErrorCallback",
    "Generative",
    "GetStateCallable",
    "IdleCallback",
    "ImageContentItem",
    "InputStateCallback",
    "JSONDict",
    "JSONSerializable",
    "LanguageResult",
    "LogCallable",
    "Manifest",
    "ManifestValue",
    "MessageCallback",
    "MessageContent",
    "MiniModel",
    "MiniPromptState",
    "ModelGenerateKwargValue",
    "ModelT",
    "NormalizerTokenizer",
    "PersonaModel",
    "PersonaProcessor",
    "PersonaTokenizer",
    "PlayCallable",
    "ProcessorKwargValue",
    "ProgressCallback",
    "QueueAvailableCallback",
    "ReleasableObject",
    "Role",
    "SayCallable",
    "SetVoiceCallable",
    "SpeechStreamItem",
    "SpeechStreamQueue",
    "StatusCallable",
    "SupportsClose",
    "SupportsUnload",
    "TerminalConfig",
    "TextConfig",
    "TextConfigValue",
    "TextContentItem",
    "TextQueueItem",
    "ThinkCallable",
    "VideoContentItem",
    "VideoInputWithMetadata",
    "VideoMetadata",
    "VideoMetadataScalar",
    "VisionInput",
    "VisionProcessorOutput",
    "VoiceChangedCallback",
    "VoiceLockStateCallback",
    "VoiceManifest",
    "VoiceMatch",
    "VramTier",
    "WaitUntilReadyCallable",
]


def __getattr__(name: str):
    """Resolve type exports lazily to avoid package import cycles."""
    module_name = _MODULE_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"{__name__}.{module_name}")
    return getattr(module, name)


def __dir__() -> list[str]:
    """Return the lazily exported package surface."""
    return __all__
