# SPDX-License-Identifier: MIT
"""Unified Celune type package with lazy re-exports."""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .agent import (
        AgentAbortReason,
        AgentApprovalDecision,
        AgentApprovalRequest,
        AgentApprovalResponse,
        AgentCancellationReason,
        AgentChoiceOption,
        AgentChoiceRequest,
        AgentChoiceResponse,
        AgentClassificationFailure,
        AgentClassificationFailureKind,
        AgentClassificationResult,
        AgentContextCompactor,
        AgentContext,
        AgentFailureReason,
        AgentInputClassification,
        AgentInterruption,
        AgentInterruptionKind,
        AgentOutput,
        AgentPermissionEvaluation,
        AgentPermissionMetadata,
        AgentPermissionPolicy,
        AgentPermissionDecision,
        AgentPermissionReason,
        AgentRequest,
        AgentResponseCallback,
        AgentResponder,
        AgentRoute,
        AgentSession,
        AgentSessionState,
        AgentTask,
        AgentTaskConfig,
        AgentTaskState,
        AgentTerminalOutcome,
        AgentTool,
        AgentToolArgumentSchema,
        AgentToolBehavior,
        AgentToolDangerLevel,
        AgentToolExecutionStatus,
        AgentToolExecutor,
        AgentToolResultHandler,
        AgentToolSchema,
        AgentToolSelector,
        AgentToolValueType,
        AgentTokenCounter,
        AgentPlanner,
        NeedleToolCall,
        NeedleToolCatalog,
        NeedleToolDefinition,
        NeedleToolParameter,
        NeedleToolParameterSpec,
        NeedleToolSelection,
        ToolCall,
        ToolExecutionResult,
        ToolResult,
        ValidatedToolCall,
    )
    from .analysis import (
        EmbeddingModel,
        EmbeddingOutput,
        EmbeddingPayload,
        EmbeddingProcessor,
        TextConfig,
        TextConfigValue,
        VoiceMatch,
    )
    from .backends import (
        BackendArgumentValue,
        BackendArguments,
        BackendDescription,
        BackendGeneration,
        BackendModel,
        MiniModel,
        MiniPromptState,
        ModelT,
    )
    from .celune import (
        CaptionCallback,
        CaptionTimingCallback,
        ErrorCallback,
        Generative,
        IdleCallback,
        InputStateCallback,
        MessageCallback,
        NormalizerTokenizer,
        ProgressCallback,
        QueueAvailableCallback,
        ReleasableObject,
        SupportsClose,
        SupportsUnload,
        VoiceChangedCallback,
        VoiceLockStateCallback,
    )
    from .cevoice import (
        Manifest,
        ManifestValue,
        VoiceManifest,
    )
    from .common import (
        JSON,
        RGB,
        Config,
        JSONSerializable,
        TerminalConfig,
        VideoMetadataScalar,
        VramTier,
    )
    from .modes import BackendMode, OperationMode
    from .locks import (
        ComponentBusyResult,
        ComponentLockAcquisition,
        ComponentLockName,
        ComponentLockOwner,
        ComponentLockRequirement,
        ComponentName,
    )
    from .extensions import (
        GetStateCallable,
        LogCallable,
        PlayCallable,
        SayCallable,
        SetVoiceCallable,
        StatusCallable,
        ThinkCallable,
        WaitUntilReadyCallable,
    )
    from .persona import (
        ChatMessagePayload,
        ChatTemplateRenderer,
        ContentItem,
        ImageContentItem,
        JSONDict,
        MessageContent,
        ModelGenerateKwargValue,
        PersonaModel,
        PersonaProcessor,
        PersonaTokenizer,
        ProcessorKwargValue,
        Role,
        TextContentItem,
        VideoContentItem,
        VideoInputWithMetadata,
        VideoMetadata,
        VisionInput,
        VisionProcessorOutput,
    )
    from .pipeline import (
        AudioChunk,
        AudioQueueItem,
        SpeechStreamItem,
        SpeechStreamQueue,
        TextQueueItem,
    )
    from .ui import (
        CeluneBaseUI,
        CeluneHeadlessBaseUI,
        CeluneTextualUI,
    )
    from .utils import (
        CallerInfo,
        LanguageResult,
    )
    from .worker import (
        WorkerArguments,
        WorkerMessage,
        WorkerMessageValue,
        WorkerRequest,
        WorkerResponse,
        WorkerValue,
    )

_MODULE_EXPORTS = {
    "AgentAbortReason": "agent",
    "AgentApprovalDecision": "agent",
    "AgentApprovalRequest": "agent",
    "AgentApprovalResponse": "agent",
    "AgentCancellationReason": "agent",
    "AgentClassificationFailure": "agent",
    "AgentClassificationFailureKind": "agent",
    "AgentClassificationResult": "agent",
    "AgentChoiceOption": "agent",
    "AgentChoiceRequest": "agent",
    "AgentChoiceResponse": "agent",
    "AgentContext": "agent",
    "AgentContextCompactor": "agent",
    "AgentFailureReason": "agent",
    "AgentInterruption": "agent",
    "AgentInterruptionKind": "agent",
    "AgentInputClassification": "agent",
    "AgentOutput": "agent",
    "AgentPermissionDecision": "agent",
    "AgentPermissionEvaluation": "agent",
    "AgentPermissionMetadata": "agent",
    "AgentPermissionPolicy": "agent",
    "AgentPermissionReason": "agent",
    "AgentPlanner": "agent",
    "AgentRequest": "agent",
    "AgentResponseCallback": "agent",
    "AgentResponder": "agent",
    "AgentSession": "agent",
    "AgentSessionState": "agent",
    "AgentTask": "agent",
    "AgentTaskConfig": "agent",
    "AgentTaskState": "agent",
    "AgentTerminalOutcome": "agent",
    "AgentTool": "agent",
    "AgentToolArgumentSchema": "agent",
    "AgentToolBehavior": "agent",
    "AgentToolDangerLevel": "agent",
    "AgentToolExecutionStatus": "agent",
    "AgentToolExecutor": "agent",
    "AgentToolResultHandler": "agent",
    "AgentToolSchema": "agent",
    "AgentToolSelector": "agent",
    "AgentToolValueType": "agent",
    "AgentTokenCounter": "agent",
    "AgentRoute": "agent",
    "AudioChunk": "pipeline",
    "AudioQueueItem": "pipeline",
    "BackendArgumentValue": "backends",
    "BackendArguments": "backends",
    "BackendDescription": "backends",
    "BackendGeneration": "backends",
    "BackendModel": "backends",
    "CallerInfo": "utils",
    "CaptionCallback": "celune",
    "CaptionTimingCallback": "celune",
    "CeluneBaseUI": "ui",
    "CeluneHeadlessBaseUI": "ui",
    "CeluneTextualUI": "ui",
    "ChatMessagePayload": "persona",
    "ChatTemplateRenderer": "persona",
    "Config": "common",
    "ContentItem": "persona",
    "EmbeddingModel": "analysis",
    "EmbeddingOutput": "analysis",
    "EmbeddingPayload": "analysis",
    "EmbeddingProcessor": "analysis",
    "ErrorCallback": "celune",
    "Generative": "celune",
    "GetStateCallable": "extensions",
    "IdleCallback": "celune",
    "ImageContentItem": "persona",
    "InputStateCallback": "celune",
    "JSON": "common",
    "JSONDict": "persona",
    "JSONSerializable": "common",
    "LanguageResult": "utils",
    "LogCallable": "extensions",
    "Manifest": "cevoice",
    "ManifestValue": "cevoice",
    "MessageCallback": "celune",
    "MessageContent": "persona",
    "MiniModel": "backends",
    "MiniPromptState": "backends",
    "ModelGenerateKwargValue": "persona",
    "ModelT": "backends",
    "NormalizerTokenizer": "celune",
    "NeedleToolCall": "agent",
    "NeedleToolCatalog": "agent",
    "NeedleToolDefinition": "agent",
    "NeedleToolParameter": "agent",
    "NeedleToolParameterSpec": "agent",
    "NeedleToolSelection": "agent",
    "BackendMode": "modes",
    "OperationMode": "modes",
    "ComponentBusyResult": "locks",
    "ComponentLockAcquisition": "locks",
    "ComponentLockName": "locks",
    "ComponentLockOwner": "locks",
    "ComponentLockRequirement": "locks",
    "ComponentName": "locks",
    "PersonaModel": "persona",
    "PersonaProcessor": "persona",
    "PersonaTokenizer": "persona",
    "PlayCallable": "extensions",
    "ProcessorKwargValue": "persona",
    "ProgressCallback": "celune",
    "QueueAvailableCallback": "celune",
    "ReleasableObject": "celune",
    "RGB": "common",
    "Role": "persona",
    "SayCallable": "extensions",
    "SetVoiceCallable": "extensions",
    "SpeechStreamItem": "pipeline",
    "SpeechStreamQueue": "pipeline",
    "StatusCallable": "extensions",
    "SupportsClose": "celune",
    "SupportsUnload": "celune",
    "TerminalConfig": "common",
    "TextConfig": "analysis",
    "TextConfigValue": "analysis",
    "TextQueueItem": "pipeline",
    "TextContentItem": "persona",
    "ThinkCallable": "extensions",
    "ToolCall": "agent",
    "ToolExecutionResult": "agent",
    "ToolResult": "agent",
    "ValidatedToolCall": "agent",
    "VideoContentItem": "persona",
    "VideoInputWithMetadata": "persona",
    "VideoMetadata": "persona",
    "VideoMetadataScalar": "common",
    "VisionInput": "persona",
    "VisionProcessorOutput": "persona",
    "VoiceChangedCallback": "celune",
    "VoiceLockStateCallback": "celune",
    "VoiceManifest": "cevoice",
    "VoiceMatch": "analysis",
    "VramTier": "common",
    "WaitUntilReadyCallable": "extensions",
    "WorkerArguments": "worker",
    "WorkerMessage": "worker",
    "WorkerMessageValue": "worker",
    "WorkerRequest": "worker",
    "WorkerResponse": "worker",
    "WorkerValue": "worker",
}

__all__ = [
    "JSON",
    "RGB",
    "AgentAbortReason",
    "AgentApprovalDecision",
    "AgentApprovalRequest",
    "AgentApprovalResponse",
    "AgentCancellationReason",
    "AgentChoiceOption",
    "AgentChoiceRequest",
    "AgentChoiceResponse",
    "AgentClassificationFailure",
    "AgentClassificationFailureKind",
    "AgentClassificationResult",
    "AgentContext",
    "AgentContextCompactor",
    "AgentFailureReason",
    "AgentInputClassification",
    "AgentInterruption",
    "AgentInterruptionKind",
    "AgentOutput",
    "AgentPermissionDecision",
    "AgentPermissionEvaluation",
    "AgentPermissionMetadata",
    "AgentPermissionPolicy",
    "AgentPermissionReason",
    "AgentPlanner",
    "AgentRequest",
    "AgentResponder",
    "AgentResponseCallback",
    "AgentRoute",
    "AgentSession",
    "AgentSessionState",
    "AgentTask",
    "AgentTaskConfig",
    "AgentTaskState",
    "AgentTerminalOutcome",
    "AgentTokenCounter",
    "AgentTool",
    "AgentToolArgumentSchema",
    "AgentToolBehavior",
    "AgentToolDangerLevel",
    "AgentToolExecutionStatus",
    "AgentToolExecutor",
    "AgentToolResultHandler",
    "AgentToolSchema",
    "AgentToolSelector",
    "AgentToolValueType",
    "AudioChunk",
    "AudioQueueItem",
    "BackendArgumentValue",
    "BackendArguments",
    "BackendDescription",
    "BackendGeneration",
    "BackendMode",
    "BackendModel",
    "CallerInfo",
    "CaptionCallback",
    "CaptionTimingCallback",
    "CeluneBaseUI",
    "CeluneHeadlessBaseUI",
    "CeluneTextualUI",
    "ChatMessagePayload",
    "ChatTemplateRenderer",
    "ComponentBusyResult",
    "ComponentLockAcquisition",
    "ComponentLockName",
    "ComponentLockOwner",
    "ComponentLockRequirement",
    "ComponentName",
    "Config",
    "ContentItem",
    "EmbeddingModel",
    "EmbeddingOutput",
    "EmbeddingPayload",
    "EmbeddingProcessor",
    "ErrorCallback",
    "Generative",
    "GetStateCallable",
    "IdleCallback",
    "ImageContentItem",
    "InputStateCallback",
    "JSONDict",
    "JSONSerializable",
    "LanguageResult",
    "LogCallable",
    "Manifest",
    "ManifestValue",
    "MessageCallback",
    "MessageContent",
    "MiniModel",
    "MiniPromptState",
    "ModelGenerateKwargValue",
    "ModelT",
    "NeedleToolCall",
    "NeedleToolCatalog",
    "NeedleToolDefinition",
    "NeedleToolParameter",
    "NeedleToolParameterSpec",
    "NeedleToolSelection",
    "NormalizerTokenizer",
    "OperationMode",
    "PersonaModel",
    "PersonaProcessor",
    "PersonaTokenizer",
    "PlayCallable",
    "ProcessorKwargValue",
    "ProgressCallback",
    "QueueAvailableCallback",
    "ReleasableObject",
    "Role",
    "SayCallable",
    "SetVoiceCallable",
    "SpeechStreamItem",
    "SpeechStreamQueue",
    "StatusCallable",
    "SupportsClose",
    "SupportsUnload",
    "TerminalConfig",
    "TextConfig",
    "TextConfigValue",
    "TextContentItem",
    "TextQueueItem",
    "ThinkCallable",
    "ToolCall",
    "ToolExecutionResult",
    "ToolResult",
    "ValidatedToolCall",
    "VideoContentItem",
    "VideoInputWithMetadata",
    "VideoMetadata",
    "VideoMetadataScalar",
    "VisionInput",
    "VisionProcessorOutput",
    "VoiceChangedCallback",
    "VoiceLockStateCallback",
    "VoiceManifest",
    "VoiceMatch",
    "VramTier",
    "WaitUntilReadyCallable",
    "WorkerArguments",
    "WorkerMessage",
    "WorkerMessageValue",
    "WorkerRequest",
    "WorkerResponse",
    "WorkerValue",
]


def __getattr__(name: str):
    """Resolve type exports lazily to avoid package import cycles."""
    module_name = _MODULE_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"{__name__}.{module_name}")
    return getattr(module, name)


def __dir__() -> list[str]:
    """Return the lazily exported package surface."""
    return __all__
