name: Build Windows

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build launcher
        shell: cmd
        run: |
          if not exist dist mkdir dist

          for /f "tokens=*" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -find VC\Auxiliary\Build\vcvars64.bat') do set "VCVARS=%%i"

          if "%VCVARS%"=="" (
            echo vcvars64.bat not found
            exit /b 1
          )

          call "%VCVARS%"

          where cl
          cl /nologo /O2 /MT launcher.c resources\celune.res /link /OUT:dist\celune.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v6
        with:
          name: Celune-Windows-x86_64
          path: dist/celune.exe
